# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 813dfa2aad8c03fcff20859e99d2e1734bdd62e235c17f33161529b934a8bbb6c5bea24a74595b84293c2c4f3b260e4946ff8cc95bad4be849d65522bad80664

test:
  secret_key_base: 1ed16bbf0ceedf7d0b2f315ec158b8fe8653f903b53faf8d23bd144bcd2d262a16f29d5f0045262ecbdb45b7d6f0e2df8ecf2ab50582d087a98bca3769969dda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
